#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('ref_gl options')

	grp.add_option('--enable-static-gl', action='store_true', dest='GL_STATIC', default=False,
		help = 'enable direct linking to opengl [default: %(default)s]')

	grp.add_option('--enable-openxr', action='store_true', dest='OPENXR', default=False,
		help = 'enable the desktop OpenXR backend [default: %(default)s]')

	# stub
	return

def configure(conf):
	conf.env.GL_STATIC = conf.options.GL_STATIC
	conf.env.OPENXR = conf.options.OPENXR
	if conf.env.GL_STATIC:
		conf.check(lib='GL')
	if conf.env.OPENXR:
		if conf.env.DEST_OS == 'linux':
			conf.check_cfg(package='openxr', args='--cflags --libs', uselib_store='OPENXR')
			conf.check(lib='GL', uselib_store='OPENXR_GL')
			conf.check(lib='X11', uselib_store='OPENXR_X11')
		elif conf.env.DEST_OS == 'win32':
			conf.check_cc(header_name='openxr/openxr.h', uselib_store='OPENXR')
			conf.check(lib='openxr_loader', uselib_store='OPENXR')
			conf.check(lib='opengl32', uselib_store='OPENXR_GL')
		else:
			conf.fatal('--enable-openxr supports Linux/GLX and Windows/WGL only')

	if conf.env.DEST_OS2 == 'android':
		conf.check_cc(lib='log')

def build(bld):
	libs = [ 'ref_common', 'engine_includes', 'werror', 'yy_thunks' ]
	# on PSVita do not link any libraries that are already in the main executable, but add the includes target
	if bld.env.DEST_OS == 'psvita':
		libs += [ 'sdk_includes', 'vgl_shim' ]
	else:
		libs += [ 'public', 'M' ]

	source = bld.path.ant_glob(['*.c', 'gl2_shim/*.c'])
	includes = '.'

	targets = {
		'ref_gl': {
			'enable':  bld.env.GL,
			'libs':    (['GL'] if bld.env.GL_STATIC else []) + (['OPENXR', 'OPENXR_GL'] + (['OPENXR_X11'] if bld.env.DEST_OS == 'linux' else []) if bld.env.OPENXR else []),
			'defines': (['XASH_GL_STATIC=1'] if bld.env.GL_STATIC else []) + (['XASH_OPENXR=1'] if bld.env.OPENXR else []),
		},
		'ref_gles1': {
			'enable':  bld.env.NANOGL,
			'libs':    ['DL', 'nanogl', 'LOG'],
			'defines': ['XASH_NANOGL=1'],
		},
		'ref_gles2': {
			'enable':  bld.env.GLWES,
			'libs':    ['DL', 'gl-wes-v2', 'LOG'],
			'defines': ['XASH_WES=1'],
		},
		'ref_gl4es': {
			'enable':  bld.env.GL4ES,
			'libs':    ['DL', 'gl4es', 'LOG'],
			'defines': ['XASH_GL_STATIC=1', 'XASH_GL4ES=1'],
		},
		'ref_gles3compat': {
			'enable':  bld.env.GLES3COMPAT,
			'libs':    [],
			'defines': ['XASH_GLES3COMPAT=1'],
		},
	}

	for k,v in targets.items():
		if not v['enable']:
			continue

		bld.shlib(source = source,
			target = k,
			includes = includes,
			use = libs + v['libs'],
			defines = v['defines'] + ['REF_DLL=1'],
			install_path = bld.env.LIBDIR)
